
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@discovery-service:8761/eureka
spring:
    kafka:
        bootstrap-servers: broker:29092
management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411