global:
    scrape_interval:     15s

scrape_configs:
    - job_name: 'product_service'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ["product-service:8080"]
            labels:
                application: 'Product Service Application'
    - job_name: 'order_service'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ["order-service:8080"]
            labels:
                application: 'Order Service Application'
    - job_name: 'inventory_service'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ["inventory-service:8080"]
            labels:
                application: 'Inventory Service Application'
