eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes[0]:
                id: product-service
                uri: lb://product-service
                predicates[0]: Path=/api/product
            routes[1]:
                id: order-service
                uri: lb://order-service
                predicates[0]: Path=/api/order
            routes[2]:
                id: discovery-service
                uri: http://eureka:password@${app.eureka-server}:8761
                predicates[0]: Path=/eureka/web
                filters[0]: SetPath=/
            routes[3]:
                id: discovery-service-static
                uri: http://eureka:password@${app.eureka-server}:8761
                predicates[0]: Path=/eureka/**
    security:
        oauth2:
            resource-server:
                jwt:
                    issuer-uri: http://localhost:8080/realms/spring-multiservices-realm
logging:
    level:
        org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

management:
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0
