server:
    port: 0

spring:
    application:
        name: order-service
    datasource:
        url: jdbc:mysql://localhost:3306/multiservices
        driver: com.mysql.jdbc.Driver
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQLDialect

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka

management:
    health:
        circuitbreaker:
            enable: true
    endpoints:
        web:
            exposure:
                include: '*'
        health:
            show-details: always
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0
resilience4j:
    circuitbreaker:
        instance:
            inventory:
                registerHealthIndicator: true
                event-consumer-buffer-size: 10
                slidingWindowType: COUNT_BASED
                slidingWindowSize: 5
                failureRateThreshold: 50
                waitDurationInOpenState: 5s
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfEnable: true
    timelimiter:
        instances:
            inventory:
                timeout-duration: 3s
    retry:
        instances:
            inventory:
                max-attempts: 3
                wait-duration: 5s


