server:
    port: 0
spring:
    application:
        name: order-service
    datasource:
        url: jdbc:mysql://localhost:3306/multiservices
        driver: com.mysql.jdbc.Driver
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQLDialect
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka