server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/multiservices
        driver: com.mysql.jdbc.Driver
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQLDialect
