server:
    port: 8080
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@discovery-service:8761/eureka
spring:
    data:
        mongodb:
        host: mongo
        port: 27017
        database: product-service
management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411