server:
    port: 0
spring:
    application:
        name: inventory-service
    datasource:
        url: jdbc:mysql://localhost:3306/inventory_service
        driver: com.mysql.jdbc.Driver
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQLDialect
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
management:
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0